config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root to sign in page if not signed in
  resources :urls, only: %i[index new create destroy]
  get '/sign_in_guest_user', to: 'application#sign_in_guest_user'
  get '/:lookup_code', to: 'urls#show'

  # sign in guest user

  authenticated :user do
    root 'urls#index', as: :authenticated_root
  end

  root to: 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.is?(:guest)

    can :manage, Url, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
  belongs_to :user
  validates :original_url, presence: true
  validates :lookup_code, uniqueness: true, allow_blank: true

  def generate_lookup_code
    loop do
      # Generate a random string of 6 characters (a-z, A-Z, 0-9)
      lookup_code = SecureRandom.alphanumeric(6)
      break lookup_code unless Url.exists?(lookup_code:)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :urls

  Roles = %w[admin user guest].freeze
  validates :role, inclusion: { in: Roles }

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    urls_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  def after_sign_up_path_for(_resource)
    urls_path
  end

  # find the current user or guest user
  def current_user
    super || guest_user
  end

  # check if the user is a guest user
  def guest_user
    User.find(session[:guest_user_id].nil? ? session[:guest_user_id] = create_guest_user.id : session[:guest_user_id])
  end

  # create guest user
  def create_guest_user
    # create a token for guest user
    token = SecureRandom.base64(15)
    user = User.new(name: 'anonymous', password: token,
                    email: "#{token}@example.com")
    user.role = 'guest'
    user.save(validate: false)
    user
  end

  # sign in guest user
  def sign_in_guest_user
    sign_in(guest_user)
    redirect_to urls_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :authenticate_user!

  def index
    @urls = Url.where(user_id: current_user.id)
  end

  def new
    @url = Url.new
  end

  def create

    return unless url_params[:original_url].present?

    @url = Url.new(url_params)
    # if signed in user, set user_id to current user else set to nil

    @url.user_id = current_user.id

    @url.clicks = 0

    lookup = @url.lookup_code

    if lookup.empty?
      lookup = @url.generate_lookup_code
    elsif Url.exists?(lookup_code: lookup)
      flash[:alert_urls] = 'This short URL already exists. Please try again.'
      redirect_to new_url_path
      return
    elsif lookup.length < 3
      flash[:alert_urls] = 'Short URL must be at least 3 characters. Please try again.'
      redirect_to new_url_path
      return
    elsif lookup.length > 16
      flash[:alert_urls] = 'Short URL must be less than 16 characters. Please try again.'
      redirect_to new_url_path
      return
    elsif lookup.match?(/\W/)
      flash[:alert_urls] = 'Short URL must be alphanumeric. Please try again.'
      redirect_to new_url_path
      return
    end
    @url.lookup_code = lookup

    if @url.save
      redirect_to urls_path
    else
      puts @url.errors.full_messages
      flash[:alert_urls] = 'there is something wrong please try again'
      render :new
    end
  end

  def show
    @url = Url.find_by(lookup_code: params[:lookup_code])
    if @url.present?
      @url.increment!(:clicks)
      redirect_to @url.original_url, allow_other_host: true
    else
      flash[:alert_urls] = 'This url does not exist'
      redirect_to root_path
    end
  end

  def destroy
    @url = Url.find(params[:id])
    @url.destroy
    redirect_to urls_path
  end

  private

  def url_params
    params.require(:url).permit(:original_url, :lookup_code)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/urls/index.html.erb
<main  class="container-wrapper">
  <div class="vh-100 wid-100 d-flex flex-column bg-secondary align-items-center bg-opacity-10">
    <div class="w-100 navbar d-flex p-3 align-items-center justify-content-between bg-primary-main">
      <p class="navbar-brand applogo fs-5 m-0 text-light">Shorty Url</p>
      <div class="d-flex justify-content-end">
        <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false }, class: "btn btn-light" %>
      </div>
    </div>
    <h3>All Links</h3>
    <ul class="list-group wid-90 url-list">
      <% @urls.each do |url| %>
        <li class="list-group-item d-flex flex-column">
          <div class="dropdown ms-auto align-self-end">
            <div class="mt-1 cursor-pointer" data-bs-toggle="dropdown" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
              </svg>
            </div>
            <ul class="dropdown-menu">
              <li class="dropdown-item text-danger">
                <%= button_to 'Delete', url_path(url), method: :delete, data: { turbo: false }, class: "text-decoration-none text-align-left text-secondary p-0 bg-transparent border-none w-100" %>
              </li>
            </ul>
          </div>
          <div class="d-flex flex-column justify-content-between pb-3">
            <div class="d-flex flex-column">
              <strong>Original url:</strong>
              <a href="<%= url.original_url %>" class="text-decoration-none text-dark break-word">
                <%= url.original_url %>
              </a>
              <strong>Shorten url:</strong>
              <div class="d-flex">
                <a href="http://localhost:3000/<%= url.lookup_code %>" class="text-decoration-none text-dark break-word" id="bar">
                  http://localhost:3000/<%= url.lookup_code %>
                </a>
                <!-- Trigger -->
                <button class="clipboard-btn btn btn-outline-success" onclick="
                navigator.clipboard.writeText('http://localhost:3000/<%= url.lookup_code %>');
                alert('Copied to clipboard');">
                  <i class="bi bi-clipboard"></i>
                </button>
              </div>
            </div>
            <div class="d-flex flex-column">
              <p class="m-0"><strong>Clicks: </strong><%= url.clicks %></p>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
    <div class="wid-90 bg-second p-3 mt-auto">
      <%= link_to "NEW LINK", new_url_path, class: "w-100 p-3 btn btn-success text-light border-light" %>
    </div>
  </div>
</main>

app/views/urls/new.html.erb
<main  class="container-wrapper">
  <div class="vh-100 wid-100 d-flex flex-column bg-secondary align-items-center bg-opacity-10">
    <div class="w-100 navbar d-flex p-3 align-items-center justify-content-between bg-primary-main">
      <p class="navbar-brand applogo fs-5 m-0 text-light">Shorty Url</p>
      <div class="d-flex justify-content-end">
        <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false }, class: "btn btn-light" %>
      </div>
    </div>
    <%= form_with(model: @url, class: "wid-90 mt-3 d-flex flex-column" ) do |f| %>
      <%# field for getting long url %>
      <div class="field form-floating mt-2 mb-3">
        <%= f.text_field :original_url, class: "form-control" %>
        <%= f.label :original_url, "Original Url", class: "form-label" %>
      </div>
      <%# field for getting custom lookup code %>
      <%= f.label :lookup_code, "http://localhost:3000/", class: "form-label m-0 p-0" %>
      <i class="text-muted m-0 p-0 fs-6">(Optional) Max 16 alphanumeric (a-z, A-Z, 0-9)</i>
      <div class="field form-floating mb-3">
        <%= f.text_field :lookup_code, class: "form-control" %>
        <%= f.label :lookup_code, "Custom alphanumeric", class: "form-label" %>
      </div>
      <% if alert %>
        <p class="alert alert-danger m-0"><%= alert_urls %></p>
      <% end %>
      <div class="actions">
        <%= f.submit "Make it short", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</main>

app/views/welcome/index.html.erb
<main class="container-wrapper">
  <div class="container">
    <span class="title-char">S</span>
    <span class="title-char">h</span>
    <span class="title-char">o</span>
    <span class="title-char">r</span>
    <span class="title-char">r</span>
    <span class="title-char">t</span>
    <span class="title-char">y</span>
    <span class="title-char">U</span>
    <span class="title-char">r</span>
    <span class="title-char">l</span>
  </div>
  <div class="p-4 vh-100 bg-secondary bg-opacity-10 d-flex flex-column align-items-center ">
    <h1 class="h-100 d-flex align-items-center justify-content-center applogo">Shorty Url</h1>
    <div class="d-flex flex-column gap-2 wid-90">
      <%= link_to 'LOG IN', '/users/sign_in', class: "btn btn-primary p-3 fw-semibold" %>
      <%# login anonymously btn%>
      <%= link_to 'LOG IN ANONYMOUSLY', '/sign_in_guest_user', class: "btn btn-primary p-3 fw-semibold" %>
      <%= link_to 'SIGN UP', '/users/sign_up', class: "btn btn-light p-3 fw-semibold" %>
    </div>
  </div>
</main>